In [1]:
import pandas as pd

#### Importing data
This code imports the data made in another jupyter notebook and drops the first column name, this column only contained a single counter value which pandas also keeps track of, so this was unnessacary. Next I show the first 5 rows to make sure it got imported correctly.

In [11]:
df = pd.read_csv("5kfiles_kt1.csv")
df = df.drop(columns=["Unnamed: 0"])
df.head(5)

       timestamp  solving_id question_id user_answer  elapsed_time  user_id
0  1565096190868           1       q5012           b         38000        1
1  1565096221062           2       q4706           c         24000        1
2  1565096293432           3       q4366           b         68000        1
3  1565096339668           4       q4829           a         42000        1
4  1565096401774           5       q6528           b         59000        1

### Question awnsers
Next I took a look at the question awnsers, in the contents table there is the correct solution to a question but I wanted to check out if I could find the correct solution based on user awnsers.

In [16]:
question_answers = df.groupby(['question_id', 'user_answer']).size()
question_answers = question_answers.unstack(fill_value=0)
question_answers

user_answer    a   b    c    d
question_id
q1             1  87    2    1
q10          112  39  159  197
q100           1   1  129    1
q1000         64  99  256    0
q10000        14  42    3   16
...          ...  ..  ...  ...
q9995          3  17    6   56
q9996         63   7    7    8
q9997          3   6   43   40
q9998         55  17    2    8
q9999          7  67    2    5

[11859 rows x 4 columns]

In [18]:
user_answer_winner = question_answers.idxmax(axis=1)
user_answer_winner

question_id
q1        b
q10       d
q100      c
q1000     c
q10000    b
         ..
q9995     d
q9996     a
q9997     c
q9998     a
q9999     b
Length: 11859, dtype: str

In [21]:
df_question_content = pd.read_csv(f"C:\\Users\\bramm\\student-grade data\\Data\\raw\\EdNet-Contents\\contents\\questions.csv")
df_question_content.head()

,question_id,bundle_id,explanation_id,correct_answer,part,tags,deployed_at
0,q1,b1,e1,b,1,1;2;179;181,1558093217098
1,q2,b2,e2,a,1,15;2;182,1558093219720
2,q3,b3,e3,b,1,14;2;179;183,1558093222784
3,q4,b4,e4,b,1,9;2;179;184,1558093225357
4,q5,b5,e5,c,1,8;2;179;181,1558093228439